# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-10 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180110_2013'),
        ('login', '0003_auto_20171109_1636'),
    ]

    operations = [
    ]
